artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/pourushkg/All_Dataset/raw/main/data2/train.csv
  local_data_dir: artifacts/data_ingestion/train.csv
  
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/train.csv
  STATUS_FILE: artifacts/data_validation/status.txt
